### ISSUE TITLE
Implementation of UWP and iOS

### ISSUE THREAD

**Issue by DumDumin** [gmlwns2000/TensorFlowSharp#2]
Hey gmlwns2000,

thanks for sharing your code based on miguels Tensorflowsharp.

I got my models running on Xamarin.Android and Windows applications based on .NET 4.6.1 with your help :) But now I wanna go the next step and also support UWP and iOS. I suppose I need do implement a native class library for both types too. Because UWP depends on .NET Core I cannot use the .NET 4.6.1 implementation of yours.

So far I haven't done anything for iOS, only tried UWP. But when building my UWP application (which includes my TensorflowSharp.UWP project, created like you did for Android and Windows) I get a building error saying: libtensorflow.dll is not loadable from the folder where TensorFlowSharp.UWP.dll is located.
And indeed, the libtensorflow.dll isn't copied into the bin folder like its done by the "normal" windows project. Coping the file into that folder by hand doesn't change anything...

Does anybody already tried to work with UWP on this topic?
Am I missing something on including the libtensorflow.dll to the native TensorFlowSharp.UWP project?

Thank you for any help or hints :)

**Comment by gmlwns2000** [comment]
Hi @DumDumin ,

In my case, I just added libtensorflow.dll into UWP Application project as Content.

Also I tried to add libtensorflow.dll into TensorFlowSharp.UWP project, because it is more easier way to use library. But it doesn't copy .dll into UWP application directory.

**Comment by DumDumin** [comment]
ah okay, adding it to the UWP application project seems to work, thanks :)
